export default {
  COLOR_FONT_PLAIN: '#0F0635',
  COLOR_UTILITIES_BACKGROUND: '#7F63FF',
  COLOR_UTILITIES_TEXT: '#FFFFFF',
  COLOR_GRAY: '#C6C5CC',
  COLOR_PRIMARY_BACKGROUND: '#FFFFFF',
  COLOR_ON_ERROR: '#ff6363',
  COLOR_ON_SUCCESS: '#63ff7a',
};
